// @generated
// This file is @generated by prost-build.
/// SaucerInit is passed from Go to the Saucer C++ process on startup.
/// Serialized as protobuf binary, base64-encoded, and passed via BLDR_SAUCER_INIT env var.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SaucerInit {
    /// DevTools enables the developer tools.
    #[prost(bool, tag="1")]
    pub dev_tools: bool,
    /// ExternalLinks configures how external links are handled.
    #[prost(enumeration="ExternalLinks", tag="2")]
    pub external_links: i32,
}
/// ExternalLinks configures how external links are handled.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ExternalLinks {
    /// EXTERNAL_LINKS_OS_BROWSER opens external links in the OS default browser.
    OsBrowser = 0,
    /// EXTERNAL_LINKS_DENY denies all external link navigation.
    Deny = 1,
}
impl ExternalLinks {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::OsBrowser => "EXTERNAL_LINKS_OS_BROWSER",
            Self::Deny => "EXTERNAL_LINKS_DENY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EXTERNAL_LINKS_OS_BROWSER" => Some(Self::OsBrowser),
            "EXTERNAL_LINKS_DENY" => Some(Self::Deny),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
