//go:build deps_only && cgo

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/aperturerobotics/bldr-saucer/saucer.proto
// Protobuf C++ Version: 6.33.4

#include "saucer.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace saucer {

inline constexpr SaucerInit::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        dev_tools_{false},
        external_links_{static_cast< ::saucer::ExternalLinks >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR SaucerInit::SaucerInit(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SaucerInit_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SaucerInitDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SaucerInitDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SaucerInitDefaultTypeInternal() {}
  union {
    SaucerInit _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SaucerInitDefaultTypeInternal _SaucerInit_default_instance_;
}  // namespace saucer
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_github_2ecom_2faperturerobotics_2fbldr_2dsaucer_2fsaucer_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_github_2ecom_2faperturerobotics_2fbldr_2dsaucer_2fsaucer_2eproto = nullptr;
const ::uint32_t
    TableStruct_github_2ecom_2faperturerobotics_2fbldr_2dsaucer_2fsaucer_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::saucer::SaucerInit, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::saucer::SaucerInit, _impl_.dev_tools_),
        PROTOBUF_FIELD_OFFSET(::saucer::SaucerInit, _impl_.external_links_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::saucer::SaucerInit)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::saucer::_SaucerInit_default_instance_._instance,
};
const char descriptor_table_protodef_github_2ecom_2faperturerobotics_2fbldr_2dsaucer_2fsaucer_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n4github.com/aperturerobotics/bldr-sauce"
    "r/saucer.proto\022\006saucer\"N\n\nSaucerInit\022\021\n\t"
    "dev_tools\030\001 \001(\010\022-\n\016external_links\030\002 \001(\0162"
    "\025.saucer.ExternalLinks*G\n\rExternalLinks\022"
    "\035\n\031EXTERNAL_LINKS_OS_BROWSER\020\000\022\027\n\023EXTERN"
    "AL_LINKS_DENY\020\001B5Z3github.com/aperturero"
    "botics/bldr-saucer;bldr_saucerb\006proto3"
};
static ::absl::once_flag descriptor_table_github_2ecom_2faperturerobotics_2fbldr_2dsaucer_2fsaucer_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_github_2ecom_2faperturerobotics_2fbldr_2dsaucer_2fsaucer_2eproto = {
    false,
    false,
    278,
    descriptor_table_protodef_github_2ecom_2faperturerobotics_2fbldr_2dsaucer_2fsaucer_2eproto,
    "github.com/aperturerobotics/bldr-saucer/saucer.proto",
    &descriptor_table_github_2ecom_2faperturerobotics_2fbldr_2dsaucer_2fsaucer_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_github_2ecom_2faperturerobotics_2fbldr_2dsaucer_2fsaucer_2eproto::offsets,
    file_level_enum_descriptors_github_2ecom_2faperturerobotics_2fbldr_2dsaucer_2fsaucer_2eproto,
    file_level_service_descriptors_github_2ecom_2faperturerobotics_2fbldr_2dsaucer_2fsaucer_2eproto,
};
namespace saucer {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ExternalLinks_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_github_2ecom_2faperturerobotics_2fbldr_2dsaucer_2fsaucer_2eproto);
  return file_level_enum_descriptors_github_2ecom_2faperturerobotics_2fbldr_2dsaucer_2fsaucer_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ExternalLinks_internal_data_[] = {
    131072u, 0u, };
// ===================================================================

class SaucerInit::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SaucerInit>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SaucerInit, _impl_._has_bits_);
};

SaucerInit::SaucerInit(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SaucerInit_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:saucer.SaucerInit)
}
SaucerInit::SaucerInit(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SaucerInit& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SaucerInit_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE SaucerInit::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void SaucerInit::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, dev_tools_),
           0,
           offsetof(Impl_, external_links_) -
               offsetof(Impl_, dev_tools_) +
               sizeof(Impl_::external_links_));
}
SaucerInit::~SaucerInit() {
  // @@protoc_insertion_point(destructor:saucer.SaucerInit)
  SharedDtor(*this);
}
inline void SaucerInit::SharedDtor(MessageLite& self) {
  SaucerInit& this_ = static_cast<SaucerInit&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SaucerInit::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SaucerInit(arena);
}
constexpr auto SaucerInit::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SaucerInit),
                                            alignof(SaucerInit));
}
constexpr auto SaucerInit::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SaucerInit_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SaucerInit::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SaucerInit>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SaucerInit::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SaucerInit>(), &SaucerInit::ByteSizeLong,
              &SaucerInit::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SaucerInit, _impl_._cached_size_),
          false,
      },
      &SaucerInit::kDescriptorMethods,
      &descriptor_table_github_2ecom_2faperturerobotics_2fbldr_2dsaucer_2fsaucer_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SaucerInit_class_data_ =
        SaucerInit::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SaucerInit::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SaucerInit_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SaucerInit_class_data_.tc_table);
  return SaucerInit_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
SaucerInit::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SaucerInit, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SaucerInit_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::saucer::SaucerInit>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .saucer.ExternalLinks external_links = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SaucerInit, _impl_.external_links_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(SaucerInit, _impl_.external_links_)}},
    // bool dev_tools = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SaucerInit, _impl_.dev_tools_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(SaucerInit, _impl_.dev_tools_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool dev_tools = 1;
    {PROTOBUF_FIELD_OFFSET(SaucerInit, _impl_.dev_tools_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // .saucer.ExternalLinks external_links = 2;
    {PROTOBUF_FIELD_OFFSET(SaucerInit, _impl_.external_links_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void SaucerInit::Clear() {
// @@protoc_insertion_point(message_clear_start:saucer.SaucerInit)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    ::memset(&_impl_.dev_tools_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.external_links_) -
        reinterpret_cast<char*>(&_impl_.dev_tools_)) + sizeof(_impl_.external_links_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SaucerInit::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SaucerInit& this_ = static_cast<const SaucerInit&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SaucerInit::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SaucerInit& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:saucer.SaucerInit)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bool dev_tools = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_dev_tools() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          1, this_._internal_dev_tools(), target);
    }
  }

  // .saucer.ExternalLinks external_links = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_external_links() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          2, this_._internal_external_links(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:saucer.SaucerInit)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SaucerInit::ByteSizeLong(const MessageLite& base) {
  const SaucerInit& this_ = static_cast<const SaucerInit&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SaucerInit::ByteSizeLong() const {
  const SaucerInit& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:saucer.SaucerInit)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // bool dev_tools = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_dev_tools() != 0) {
        total_size += 2;
      }
    }
    // .saucer.ExternalLinks external_links = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_external_links() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_external_links());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SaucerInit::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<SaucerInit*>(&to_msg);
  auto& from = static_cast<const SaucerInit&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:saucer.SaucerInit)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (from._internal_dev_tools() != 0) {
        _this->_impl_.dev_tools_ = from._impl_.dev_tools_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_external_links() != 0) {
        _this->_impl_.external_links_ = from._impl_.external_links_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void SaucerInit::CopyFrom(const SaucerInit& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:saucer.SaucerInit)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SaucerInit::InternalSwap(SaucerInit* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SaucerInit, _impl_.external_links_)
      + sizeof(SaucerInit::_impl_.external_links_)
      - PROTOBUF_FIELD_OFFSET(SaucerInit, _impl_.dev_tools_)>(
          reinterpret_cast<char*>(&_impl_.dev_tools_),
          reinterpret_cast<char*>(&other->_impl_.dev_tools_));
}

::google::protobuf::Metadata SaucerInit::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace saucer
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_github_2ecom_2faperturerobotics_2fbldr_2dsaucer_2fsaucer_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
