// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/aperturerobotics/bldr-saucer/saucer.proto (package saucer, syntax proto3)
/* eslint-disable */

import type { MessageType, PartialFieldInfo } from '@aptre/protobuf-es-lite'
import {
  createEnumType,
  createMessageType,
  ScalarType,
} from '@aptre/protobuf-es-lite'

export const protobufPackage = 'saucer'

/**
 * ExternalLinks configures how external links are handled.
 *
 * @generated from enum saucer.ExternalLinks
 */
export enum ExternalLinks {
  /**
   * EXTERNAL_LINKS_OS_BROWSER opens external links in the OS default browser.
   *
   * @generated from enum value: EXTERNAL_LINKS_OS_BROWSER = 0;
   */
  OS_BROWSER = 0,

  /**
   * EXTERNAL_LINKS_DENY denies all external link navigation.
   *
   * @generated from enum value: EXTERNAL_LINKS_DENY = 1;
   */
  DENY = 1,
}

// ExternalLinks_Enum is the enum type for ExternalLinks.
export const ExternalLinks_Enum = createEnumType('saucer.ExternalLinks', [
  { no: 0, name: 'EXTERNAL_LINKS_OS_BROWSER' },
  { no: 1, name: 'EXTERNAL_LINKS_DENY' },
])

/**
 * SaucerInit is passed from Go to the Saucer C++ process on startup.
 * Serialized as protobuf binary, base64-encoded, and passed via BLDR_SAUCER_INIT env var.
 *
 * @generated from message saucer.SaucerInit
 */
export interface SaucerInit {
  /**
   * DevTools enables the developer tools.
   *
   * @generated from field: bool dev_tools = 1;
   */
  devTools?: boolean
  /**
   * ExternalLinks configures how external links are handled.
   *
   * @generated from field: saucer.ExternalLinks external_links = 2;
   */
  externalLinks?: ExternalLinks
}

// SaucerInit contains the message type declaration for SaucerInit.
export const SaucerInit: MessageType<SaucerInit> = createMessageType({
  typeName: 'saucer.SaucerInit',
  fields: [
    { no: 1, name: 'dev_tools', kind: 'scalar', T: ScalarType.BOOL },
    { no: 2, name: 'external_links', kind: 'enum', T: ExternalLinks_Enum },
  ] as readonly PartialFieldInfo[],
  packedByDefault: true,
})
