// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: v0.12.1
// source: github.com/aperturerobotics/bldr-saucer/saucer.proto

package bldr_saucer

import (
	fmt "fmt"
	io "io"
	slices "slices"
	strconv "strconv"
	strings "strings"

	protobuf_go_lite "github.com/aperturerobotics/protobuf-go-lite"
	json "github.com/aperturerobotics/protobuf-go-lite/json"
)

// ExternalLinks configures how external links are handled.
type ExternalLinks int32

const (
	// EXTERNAL_LINKS_OS_BROWSER opens external links in the OS default browser.
	ExternalLinks_EXTERNAL_LINKS_OS_BROWSER ExternalLinks = 0
	// EXTERNAL_LINKS_DENY denies all external link navigation.
	ExternalLinks_EXTERNAL_LINKS_DENY ExternalLinks = 1
)

// Enum value maps for ExternalLinks.
var (
	ExternalLinks_name = map[int32]string{
		0: "EXTERNAL_LINKS_OS_BROWSER",
		1: "EXTERNAL_LINKS_DENY",
	}
	ExternalLinks_value = map[string]int32{
		"EXTERNAL_LINKS_OS_BROWSER": 0,
		"EXTERNAL_LINKS_DENY":       1,
	}
)

func (x ExternalLinks) Enum() *ExternalLinks {
	p := new(ExternalLinks)
	*p = x
	return p
}

func (x ExternalLinks) String() string {
	name, valid := ExternalLinks_name[int32(x)]
	if valid {
		return name
	}
	return strconv.Itoa(int(x))
}

// SaucerInit is passed from Go to the Saucer C++ process on startup.
// Serialized as protobuf binary, base64-encoded, and passed via BLDR_SAUCER_INIT env var.
type SaucerInit struct {
	unknownFields []byte
	// DevTools enables the developer tools.
	DevTools bool `protobuf:"varint,1,opt,name=dev_tools,json=devTools,proto3" json:"devTools,omitempty"`
	// ExternalLinks configures how external links are handled.
	ExternalLinks ExternalLinks `protobuf:"varint,2,opt,name=external_links,json=externalLinks,proto3" json:"externalLinks,omitempty"`
}

func (x *SaucerInit) Reset() {
	*x = SaucerInit{}
}

func (*SaucerInit) ProtoMessage() {}

func (x *SaucerInit) GetDevTools() bool {
	if x != nil {
		return x.DevTools
	}
	return false
}

func (x *SaucerInit) GetExternalLinks() ExternalLinks {
	if x != nil {
		return x.ExternalLinks
	}
	return ExternalLinks_EXTERNAL_LINKS_OS_BROWSER
}

func (m *SaucerInit) CloneVT() *SaucerInit {
	if m == nil {
		return (*SaucerInit)(nil)
	}
	r := new(SaucerInit)
	r.DevTools = m.DevTools
	r.ExternalLinks = m.ExternalLinks
	if len(m.unknownFields) > 0 {
		r.unknownFields = slices.Clone(m.unknownFields)
	}
	return r
}

func (m *SaucerInit) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (this *SaucerInit) EqualVT(that *SaucerInit) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.DevTools != that.DevTools {
		return false
	}
	if this.ExternalLinks != that.ExternalLinks {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *SaucerInit) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*SaucerInit)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}

// MarshalProtoJSON marshals the ExternalLinks to JSON.
func (x ExternalLinks) MarshalProtoJSON(s *json.MarshalState) {
	s.WriteEnum(int32(x), ExternalLinks_name)
}

// MarshalText marshals the ExternalLinks to text.
func (x ExternalLinks) MarshalText() ([]byte, error) {
	return []byte(json.GetEnumString(int32(x), ExternalLinks_name)), nil
}

// MarshalJSON marshals the ExternalLinks to JSON.
func (x ExternalLinks) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the ExternalLinks from JSON.
func (x *ExternalLinks) UnmarshalProtoJSON(s *json.UnmarshalState) {
	v := s.ReadEnum(ExternalLinks_value)
	if err := s.Err(); err != nil {
		s.SetErrorf("could not read ExternalLinks enum: %v", err)
		return
	}
	*x = ExternalLinks(v)
}

// UnmarshalText unmarshals the ExternalLinks from text.
func (x *ExternalLinks) UnmarshalText(b []byte) error {
	i, err := json.ParseEnumString(string(b), ExternalLinks_value)
	if err != nil {
		return err
	}
	*x = ExternalLinks(i)
	return nil
}

// UnmarshalJSON unmarshals the ExternalLinks from JSON.
func (x *ExternalLinks) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the SaucerInit message to JSON.
func (x *SaucerInit) MarshalProtoJSON(s *json.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.DevTools || s.HasField("devTools") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("devTools")
		s.WriteBool(x.DevTools)
	}
	if x.ExternalLinks != 0 || s.HasField("externalLinks") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("externalLinks")
		x.ExternalLinks.MarshalProtoJSON(s)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the SaucerInit to JSON.
func (x *SaucerInit) MarshalJSON() ([]byte, error) {
	return json.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the SaucerInit message from JSON.
func (x *SaucerInit) UnmarshalProtoJSON(s *json.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.Skip() // ignore unknown field
		case "dev_tools", "devTools":
			s.AddField("dev_tools")
			x.DevTools = s.ReadBool()
		case "external_links", "externalLinks":
			s.AddField("external_links")
			x.ExternalLinks.UnmarshalProtoJSON(s)
		}
	})
}

// UnmarshalJSON unmarshals the SaucerInit from JSON.
func (x *SaucerInit) UnmarshalJSON(b []byte) error {
	return json.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

func (m *SaucerInit) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SaucerInit) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *SaucerInit) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.ExternalLinks != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.ExternalLinks))
		i--
		dAtA[i] = 0x10
	}
	if m.DevTools {
		i--
		if m.DevTools {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SaucerInit) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DevTools {
		n += 2
	}
	if m.ExternalLinks != 0 {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(m.ExternalLinks))
	}
	n += len(m.unknownFields)
	return n
}

func (x ExternalLinks) MarshalProtoText() string {
	return x.String()
}

func (x *SaucerInit) MarshalProtoText() string {
	var sb strings.Builder
	sb.WriteString("SaucerInit {")
	if x.DevTools != false {
		if sb.Len() > 12 {
			sb.WriteString(" ")
		}
		sb.WriteString("dev_tools: ")
		sb.WriteString(strconv.FormatBool(x.DevTools))
	}
	if x.ExternalLinks != 0 {
		if sb.Len() > 12 {
			sb.WriteString(" ")
		}
		sb.WriteString("external_links: ")
		sb.WriteString("\"")
		sb.WriteString(ExternalLinks(x.ExternalLinks).String())
		sb.WriteString("\"")
	}
	sb.WriteString("}")
	return sb.String()
}

func (x *SaucerInit) String() string {
	return x.MarshalProtoText()
}

func (m *SaucerInit) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	var err error
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		wire, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
		if err != nil {
			return err
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SaucerInit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SaucerInit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DevTools", wireType)
			}
			var v int
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			v = int(_v)
			if err != nil {
				return err
			}
			m.DevTools = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExternalLinks", wireType)
			}
			m.ExternalLinks = 0
			var _v uint64
			_v, iNdEx, err = protobuf_go_lite.DecodeVarint(dAtA, iNdEx)
			m.ExternalLinks = ExternalLinks(_v)
			if err != nil {
				return err
			}
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
